[package]
name = "git-nexus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
colored = "3.1.1"
git2 = { version = "0.20.4", default-features = false }
walkdir = "2.5.0"
